### ISSUE TITLE
defoldprofiler doesn't return any data

### ISSUE THREAD

**Issue by Jerakin** [britzl/defpro#1]
Simple sample

```
local profiler			= require "defpro.defoldprofiler"

function init(self)
	profiler.capture(1, "127.0.0.1", function(frames)
		pprint(frames)
	end)
end
```

____
Seems to be because https://github.com/britzl/defpro/blob/38f529ad26ed002fcfc0665b5d67c5995a85a3b3/defpro/defoldprofiler.lua#L15 no longer returns a proper response

___
printing the response from `http.request` gives
```
{ --[[0x142fddc0]]
  status = 302,
  response = "",
  headers = { --[[0x142fde30]]
    location = "ttp://172.22.4.108:59437/strings",
    server = "Dynamo 1.0",
    transfer-encoding = "chunked",
    cache-control = "o-store"
  }
}
```

**Comment by britzl** [comment]
Fixed in https://github.com/britzl/defpro/releases/tag/1.0.2
